name: snake
channels:
  - conda-forge
  - anaconda
  - defaults
  - bioconda
dependencies:
  - python=3.11.0
  - snakemake=7.18.2
  - pyyaml=6.0
  - pandas=1.5.2
  - biopython=1.80
  - bcftools=1.15.1
  - htslib=1.15.1
  - tabix=1.11
  - libopenblas=0.3.21